class RepositorioEmprestimo:

    def buscar_equipamento(self, equip_id):
        ...

    def salvar_emprestimo(self, emprestimo):
        ...

    def marcar_indisponivel(self, equip_id):
        ...

    def buscar_emprestimo(self, emprestimo_id):
        ...

    def marcar_disponivel(self, equip_id):
        ...

    def finalizar_emprestimo(self, emprestimo_id):
        ...

    def buscar_emprestimos(self):
        ...